"""add_generation_tracking

Revision ID: 45d271720390
Revises: 480ef2308d68
Create Date: 2025-12-06 14:40:40.864586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45d271720390'
down_revision: Union[str, None] = '480ef2308d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='generationstatus').create(op.get_bind())
    sa.Enum('QUEUED', 'GENERATING', 'REVIEWING', 'FIXING', 'SAVING', 'COMPLETED', name='generationstep').create(op.get_bind())
    sa.Enum('GENERATE', 'REVIEW', 'FIX', name='loggenerationstep').create(op.get_bind())
    op.create_table('generation_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('step', postgresql.ENUM('GENERATE', 'REVIEW', 'FIX', name='loggenerationstep', create_type=False), nullable=False),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parsed_response', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_logs_recipe_id'), 'generation_logs', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_generation_logs_workflow_id'), 'generation_logs', ['workflow_id'], unique=False)
    op.add_column('recipes', sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('recipes', sa.Column('generation_step', postgresql.ENUM('QUEUED', 'GENERATING', 'REVIEWING', 'FIXING', 'SAVING', 'COMPLETED', name='generationstep', create_type=False), nullable=True))
    op.add_column('recipes', sa.Column('generation_status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='generationstatus', create_type=False), nullable=True))
    op.add_column('recipes', sa.Column('generation_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('recipes', sa.Column('generation_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_recipes_generation_status'), 'recipes', ['generation_status'], unique=False)
    op.create_index(op.f('ix_recipes_generation_step'), 'recipes', ['generation_step'], unique=False)
    op.create_index(op.f('ix_recipes_workflow_id'), 'recipes', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_workflow_id'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_generation_step'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_generation_status'), table_name='recipes')
    op.drop_column('recipes', 'generation_prompt')
    op.drop_column('recipes', 'generation_error')
    op.drop_column('recipes', 'generation_status')
    op.drop_column('recipes', 'generation_step')
    op.drop_column('recipes', 'workflow_id')
    op.drop_index(op.f('ix_generation_logs_workflow_id'), table_name='generation_logs')
    op.drop_index(op.f('ix_generation_logs_recipe_id'), table_name='generation_logs')
    op.drop_table('generation_logs')
    sa.Enum('GENERATE', 'REVIEW', 'FIX', name='loggenerationstep').drop(op.get_bind())
    sa.Enum('QUEUED', 'GENERATING', 'REVIEWING', 'FIXING', 'SAVING', 'COMPLETED', name='generationstep').drop(op.get_bind())
    sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='generationstatus').drop(op.get_bind())
    # ### end Alembic commands ###
