"""init

Revision ID: 480ef2308d68
Revises: 0
Create Date: 2025-11-30 21:24:13.763992

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '480ef2308d68'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None




def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text(
        "CREATE EXTENSION IF NOT EXISTS vector;"
    ))

    foodtype_enum = sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'DESSERT', 'SNACK', 'DRINK', name='foodtype')
    recipestatus_enum = sa.Enum('PUBLISHED', 'DRAFT', name='recipestatus')

    op.create_table('recipes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ingredients', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('food_type', foodtype_enum, nullable=True),
    sa.Column('status', recipestatus_enum, nullable=False),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('description_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('ingredient_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('favorite_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_description_embedding', 'recipes', ['description_embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'description_embedding': 'vector_cosine_ops'})
    op.create_index('idx_ingredient_embedding', 'recipes', ['ingredient_embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'ingredient_embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_recipes_created_by'), 'recipes', ['created_by'], unique=False)
    op.create_index(op.f('ix_recipes_name'), 'recipes', ['name'], unique=False)
    op.create_index(op.f('ix_recipes_status'), 'recipes', ['status'], unique=False)
    op.create_table('user_recipe_interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_liked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_recipe_unique', 'user_recipe_interactions', ['user_id', 'recipe_id'], unique=True)
    op.create_index(op.f('ix_user_recipe_interactions_recipe_id'), 'user_recipe_interactions', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_user_recipe_interactions_user_id'), 'user_recipe_interactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_recipe_interactions_user_id'), table_name='user_recipe_interactions')
    op.drop_index(op.f('ix_user_recipe_interactions_recipe_id'), table_name='user_recipe_interactions')
    op.drop_index('idx_user_recipe_unique', table_name='user_recipe_interactions')
    op.drop_table('user_recipe_interactions')
    op.drop_index(op.f('ix_recipes_status'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_name'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_created_by'), table_name='recipes')
    op.drop_index('idx_ingredient_embedding', table_name='recipes', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'ingredient_embedding': 'vector_cosine_ops'})
    op.drop_index('idx_description_embedding', table_name='recipes', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'description_embedding': 'vector_cosine_ops'})
    op.drop_table('recipes')
    # ### end Alembic commands ###
